public class Address {
  public void homeAddress(){
    string myName = 'Tugba';
    Integer numberOfFamilyMembers = 4;
    string houseName = 'Bahar Family';
    integer houseNumber = 301;
    string streetName = 'Altamonte Spring';
    string cityName = 'Orlando';
    string stateName = 'Florida';
    string stateIDNumber = ' 35161';
    string countryName = 'United States';
    string countryISOCode = 'US';
    integer zipCode =5484;
    boolean currentHome = true;

    System.debug('My name is '+myName);
    System.debug('Number of my family members '+ numberOfFamilyMembers);
    System.debug('House name '+houseName);
    system.debug('Street name '+ streetName);
    system.debug('City name '+cityName);
    system.debug('State name '+ stateName);
    system.debug('Orlando`s ISO Code is '+ stateIDNumber);
    system.debug('Country name: '+ countryName);
    System.debug('United States ISO Code is '+countryISOCode);
    System.debug('My zip code: '+zipCode);
    System.debug('Is this my current home?'+currentHome);
 
 }

}
