public class chechDatatypes {
    public void MethodBoolean(){
 Boolean checkBoolean =true;
 system.debug(checkBoolean);
}
public void MethodInteger(){
    integer varfirst =1;
    integer varsecond = 2;
    system.debug(varfirst);
    system.debug(varsecond);
}
public void StringMethod(){
    string varName = 'Tugba';
    string var2Name = 'Bahar';
    system.debug(varName);
    system.debug(var2Name);
}
}
