public class playingWithDates {
    
    public void printDateOutput(){

date dt1 = date.today();
date dt2 = date.newInstance(2789, 11, 5);
date dt3 = date.newInstance(1459,3 ,4 );
integer dayint =(20);
integer monthint = (12);
integer yearint = (2023);
date newInt = date.newInstance(yearint, monthint, dayint);
system.debug('Today date is  '+dt1);
system.debug(dt2);
system.debug(dt3);
system.debug(newInt);






    }
}
