public class turkishLesson {
    public Integer method1(string text){
        Integer uzunluk = text.length();
        return uzunluk;

    }
    public integer method2 (integer x){
        string sInteger = string.valueOf(x);
        integer rakamSys = sInteger.length();
        return rakamSys;
    }

    public integer sum(integer a, integer b){
    return a+b;
    }
    public Integer mult(integer x,integer y){
        return x*y;
        
    }
}
