ogrenci s1 = new ogrenci();
s1.firstName = 'Mary';
s1.lastName = 'Doe';
s1.className = '6e';
s1.art = True;
s1.sports = False;
s1.mathGread = 85;
s1.fenGread = 95;
s1.language = 'English';

system.debug(s1);
ogrenci s2 = new ogrenci();
s2.firstName = 'john';
s2.lastName = 'Doe';
s2.className = '6k';
s2.art = True;
s2.sports = False;
s2.mathGread = 75;
s2.fenGread = 90;   za
s2.language = 'English';

system.debug(s2); 