map<string, email_domain__mdt> allEmailDomains = email_domain__mdt.getAll();
system.debug(allEmailDomains);


/*|{"hotmail":{"IsProtected":false,"Label":"hotmail","MasterLabel":"hotmail","Language":"en_US","ManageableState":"U","QualifiedApiName":"hotmail","Id":"m008Z000000MAtx","DeveloperName":"hotmail"}

"gmail":{"IsProtected":false,"Label":"gmail","MasterLabel":"gmail","Language":"en_US","ManageableState":"U","QualifiedApiName":"gmail","Id":"m008Z000000MAts","DeveloperName":"gmail"}}*/